'use strict';
const $=id=>document.getElementById(id);
const names=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const library=[
['Sentadilla goblet','Sostén una mancuerna junto al pecho. Lleva la cadera atrás y baja con control.'],
['Press de pecho con mancuernas','En banco plano, baja las mancuernas a los lados del pecho y empuja sin rebotar.'],
['Remo en polea baja','Siéntate con la espalda estable; lleva el agarre hacia el abdomen sin balancearte.'],
['Peso muerto rumano con mancuernas','Rodillas ligeramente flexionadas. Lleva la cadera atrás y mantén las pesas cerca del cuerpo.'],
['Jalón al pecho','Desde la polea alta, baja el agarre hacia el pecho; no tires detrás del cuello.'],
['Press de hombros sentado','Con el respaldo estable, empuja las mancuernas hacia arriba sin arquear la espalda.'],
['Elevaciones laterales','Con una carga ligera, eleva los brazos hasta una altura cómoda sin balancearte.'],
['Tríceps en polea','Mantén los codos cerca del cuerpo y extiende los brazos con control.'],
['Curl de bíceps','Mantén los codos junto al cuerpo y sube las mancuernas sin mover el tronco.'],
['Zancada atrás con mancuernas','Da un paso atrás y baja con control. Empieza sin peso si necesitas equilibrio.'],
['Caminata en caminadora','Usa una velocidad cómoda que te permita conversar. Familiarízate con la parada de emergencia.'],
['Dead bug','Boca arriba, baja brazo y pierna contrarios sin despegar la zona lumbar.'],
['Gato–vaca','En cuatro apoyos, redondea y extiende suavemente la espalda.'],
['Postura del niño','Lleva la cadera hacia los talones y estira los brazos sin forzar.'],
['Split squat con apoyo','Sin mancuernas. Un pie adelante y otro atrás, ambos en el suelo. Sujétate del rack, baja poco y mantén el tronco estable. Solo si no provoca dolor lumbar; si molesta, omítelo.'],
['Puente de glúteos en el suelo','Sin peso. Eleva la cadera hasta alinear muslos y tronco, sin arquear la espalda. Si provoca dolor lumbar, omítelo.'],
['Elevación de talones con apoyo','Sujétate del rack. Eleva y baja los talones con control, sin balancearte.']];
const ex=(image,dose,seconds=90,work=0)=>({id:crypto.randomUUID(),image,name:library[image][0],tip:library[image][1],dose,seconds,work});
const inTurn=(exercise,session)=>({...exercise,session});
const strength=(image,dose,rest)=>inTurn(ex(image,dose,rest),1);
const warmup=()=>inTurn(ex(10,'5 min · calentamiento',30,300),1);
const cardio=seconds=>inTurn(ex(10,`${seconds/60} min · caminata conversacional`,30,seconds),2);
const push=label=>({title:`Push ${label} · pecho, hombros y tríceps`,focus:'PPL / DOS TURNOS',description:'Turno 1: musculación 25–40 min. Turno 2: caminata 15 min. Deja 3 repeticiones en reserva al retomar; haz 1–2 series ligeras antes del primer press.',exercises:[warmup(),strength(1,'2 × 8–12 repeticiones',120),strength(5,'2 × 8–12 repeticiones',120),strength(6,'2 × 12–15 repeticiones',90),strength(7,'2 × 10–15 repeticiones',90),cardio(900)]});
const pull=label=>({title:`Pull ${label} · espalda y bíceps`,focus:'PPL / DOS TURNOS',description:'Turno 1: musculación 25–35 min. Turno 2: caminata 15 min. Haz 1–2 series ligeras de jalón. No balancees el tronco; omite el remo si provoca dolor lumbar.',exercises:[warmup(),strength(4,'2 × 8–12 repeticiones',120),strength(2,'2 × 10–12 repeticiones',120),strength(8,'2 × 10–15 repeticiones',90),cardio(900)]});
const legs=label=>({title:`Legs ${label} · piernas con apoyo`,focus:'PPL / DOS TURNOS',description:'Turno 1: piernas 25–35 min. Turno 2: caminata 15 min. Sin sentadillas cargadas ni peso muerto. Empieza sin peso y omite cualquier movimiento que provoque dolor lumbar.',exercises:[warmup(),strength(14,'2 × 8–10 por lado',120),strength(15,'2 × 10–15 repeticiones',90),strength(16,'2 × 12–15 repeticiones',60),cardio(900)]});
const base=[push('A'),pull('A'),legs('A'),push('B'),pull('B'),legs('B'),{title:'Recuperación · descansar y moverte',focus:'DOMINGO / RECUPERACIÓN',description:'Hoy no hay musculación programada. Camina suavemente si te apetece y no duele; descansar también es válido.',exercises:[{...cardio(1200),dose:'20 min suaves · opcional'}]}];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let storageOk=true;function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{if(storageOk){storageOk=false;toast('No se pudo guardar en este navegador.')}}}
let routine=read('rutina-plan-ppl-turnos-v3',null);if(!Array.isArray(routine)||routine.length!==7){routine=base;save('rutina-plan-ppl-turnos-v3',routine)}
const now=new Date();const monday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-(now.getDay()+6)%7);const dateKey=d=>`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;const weekKey='rutina-checks-'+dateKey(monday);let checks=read(weekKey,{});let day=(now.getDay()+6)%7;
let timer=read('rutina-timer-v1',{status:'idle',duration:60,remaining:60,end:0,title:'Descanso',exercise:''});let announced=false;let audio;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
function persistTimer(){save('rutina-timer-v1',timer)}
function remaining(){return timer.status==='running'?Math.max(0,Math.ceil((timer.end-Date.now())/1000)):timer.remaining}
function beep(){try{if(!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=660;gain.gain.value=.12;osc.start();gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.5);osc.stop(audio.currentTime+.5)}catch{}}
function enableAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}}
function tick(){let secs=remaining();if(timer.status==='running'&&secs===0){timer.status='finished';timer.remaining=0;persistTimer();if(!announced){beep();announced=true}}
$('clock').textContent=`${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`;$('timer-title').textContent=timer.title;$('timer-exercise').textContent=timer.exercise||'Elige un descanso para empezar.';$('timer-state').textContent=({idle:'Listo cuando tú estés',running:'En marcha',paused:'En pausa',finished:timer.title==='Descanso'?'Descanso terminado. Continúa cuando estés listo.':'Tiempo terminado.'})[timer.status];$('pause').disabled=!['running','paused'].includes(timer.status);$('pause').textContent=timer.status==='paused'?'Continuar':'Pausar';$('start').textContent=timer.status==='running'?'Volver a empezar':'Iniciar '+timer.title.toLowerCase();document.title=timer.status==='running'?`${$('clock').textContent} · ${timer.title}`:'Mi semana · Rutina';}
function configure(seconds,title='Descanso',exercise=''){timer={status:'idle',duration:seconds,remaining:seconds,end:0,title,exercise};announced=false;persistTimer();$('custom').value=seconds;document.querySelectorAll('[data-seconds]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.seconds)===seconds));tick()}
function start(seconds=timer.duration,title=timer.title,exercise=timer.exercise){enableAudio();configure(seconds,title,exercise);timer.status='running';timer.end=Date.now()+seconds*1000;persistTimer();tick()}
function render(){const selected=routine[day];$('week-label').textContent='SEMANA DEL '+monday.toLocaleDateString('es-PE',{day:'numeric',month:'long'}).toUpperCase();$('days').replaceChildren();names.forEach((name,i)=>{const date=new Date(monday);date.setDate(date.getDate()+i);const b=document.createElement('button');b.className=i===day?'active':'';b.setAttribute('aria-pressed',String(i===day));const completed=routine[i].exercises.filter(e=>checks[e.id]).length;b.innerHTML=`<span>${name.slice(0,3)}</span><strong>${date.getDate()}</strong><small>${completed}/${routine[i].exercises.length}</small>`;b.onclick=()=>{day=i;render()};$('days').append(b)});
$('focus').textContent=selected.focus;$('day-title').textContent=selected.title;$('day-description').textContent=selected.description;const completed=selected.exercises.filter(e=>checks[e.id]).length;$('progress').textContent=`${completed} / ${selected.exercises.length}`;$('progress-bar').style.width=(selected.exercises.length?completed/selected.exercises.length*100:0)+'%';$('weekly').textContent=routine.flatMap(d=>d.exercises).filter(e=>checks[e.id]).length;$('exercises').replaceChildren();
let shownTurn=0;const orderedExercises=[...selected.exercises].sort((a,b)=>(a.session||1)-(b.session||1));orderedExercises.forEach(e=>{const turn=e.session||1;if(turn!==shownTurn){shownTurn=turn;const title=document.createElement('h3');title.className='turn-heading';title.textContent=turn===1?'Turno 1 · Musculación':'Turno 2 · Movimiento / cardio';$('exercises').append(title)}const card=document.createElement('article');card.className='exercise'+(checks[e.id]?' done':'');const image=document.createElement('img');image.src=`assets/chibi-${e.image}.webp`;image.alt='Ilustración de '+library[e.image][0];image.width=120;image.height=95;const imageButton=document.createElement('button');imageButton.className='image-button';imageButton.setAttribute('aria-label','Ver ilustración de '+e.name);imageButton.append(image);imageButton.onclick=()=>{$('image-title').textContent=e.name;$('large-image').src=image.src;$('large-image').alt=image.alt;$('image-tip').textContent=e.tip;$('image-view').showModal()};const body=document.createElement('div');const heading=document.createElement('h3');heading.textContent=e.name;const dose=document.createElement('p');dose.className='dose';dose.textContent=e.dose;const tip=document.createElement('p');tip.className='tip';tip.textContent=e.tip;const actions=document.createElement('div');actions.className='exercise-actions';const rest=document.createElement('button');rest.textContent=`Descansar ${e.seconds} s`;rest.onclick=()=>start(e.seconds,'Descanso',e.name);actions.append(rest);const guideButton=document.createElement('button');guideButton.textContent='Guiar con voz';guideButton.onclick=()=>window.openGuide(e);actions.append(guideButton);const logButton=document.createElement('button');logButton.textContent='Registrar peso';logButton.onclick=()=>window.openTrainingLog(e);if(e.image<=9||e.image>=14)actions.append(logButton);if(e.work){const work=document.createElement('button');work.textContent='Cronometrar ejercicio';work.onclick=()=>start(e.work,'Ejercicio',e.name);actions.append(work)}body.append(heading,dose,tip,actions);const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=!!checks[e.id];input.setAttribute('aria-label','Completado: '+e.name);input.onchange=()=>{checks[e.id]=input.checked;save(weekKey,checks);render()};const mark=document.createElement('span');mark.textContent='✓';label.append(input,mark);card.append(imageButton,body,label);$('exercises').append(card)});if(!selected.exercises.length){const p=document.createElement('p');p.textContent='Día libre. Puedes añadir ejercicios con «Editar este día».';$('exercises').append(p)}}
$('start').onclick=()=>start();$('pause').onclick=()=>{if(timer.status==='running'){timer.remaining=remaining();timer.status='paused'}else if(timer.status==='paused'){enableAudio();timer.end=Date.now()+timer.remaining*1000;timer.status='running'}persistTimer();tick()};$('reset').onclick=()=>configure(timer.duration,timer.title,timer.exercise);document.querySelectorAll('[data-seconds]').forEach(b=>b.onclick=()=>configure(Number(b.dataset.seconds)));$('custom').onchange=()=>{const value=Number($('custom').value);if(!Number.isInteger(value)||value<1||value>7200){$('custom').value=timer.duration;toast('Elige entre 1 y 7200 segundos.');return}configure(value)};
let draft=[];const field=(label,type,value,min,max)=>{const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type=type;input.value=value;if(min!==undefined)input.min=min;if(max!==undefined)input.max=max;input.required=true;l.append(input);return[l,input]};
function editRows(){ $('edit-rows').replaceChildren();draft.forEach((e,i)=>{const row=document.createElement('div');row.className='edit-row';const [name,n]=field('Ejercicio','text',e.name);n.maxLength=100;n.oninput=()=>e.name=n.value;const [dose,d]=field('Series / repeticiones','text',e.dose);d.maxLength=100;d.oninput=()=>e.dose=d.value;const [rest,r]=field('Descanso (s)','number',e.seconds,1,7200);r.oninput=()=>e.seconds=Number(r.value);const remove=document.createElement('button');remove.type='button';remove.className='remove';remove.textContent='✕';remove.setAttribute('aria-label','Quitar '+e.name);remove.onclick=()=>{draft.splice(i,1);editRows()};const imageLabel=document.createElement('label');imageLabel.className='wide';imageLabel.textContent='Ilustración de referencia';const select=document.createElement('select');library.forEach((l,index)=>{const o=document.createElement('option');o.value=index;o.textContent=l[0];o.selected=index===e.image;select.append(o)});select.onchange=()=>{e.image=Number(select.value)};imageLabel.append(select);const [tip,t]=field('Cómo hacerlo','text',e.tip);tip.className='wide';t.maxLength=300;t.oninput=()=>e.tip=t.value;const turnLabel=document.createElement('label');turnLabel.className='wide';turnLabel.textContent='Turno';const turnSelect=document.createElement('select');for(const [value,text] of [[1,'Turno 1 · Musculación'],[2,'Turno 2 · Movimiento / cardio']]){const option=document.createElement('option');option.value=value;option.textContent=text;option.selected=value===(e.session||1);turnSelect.append(option)}turnSelect.onchange=()=>e.session=Number(turnSelect.value);turnLabel.append(turnSelect);const [work,w]=field('Duración del ejercicio (s; 0 = por repeticiones)','number',e.work,0,7200);work.className='wide';w.oninput=()=>e.work=Number(w.value);row.append(name,dose,rest,remove,turnLabel,imageLabel,tip,work);$('edit-rows').append(row)})}
$('edit').onclick=()=>{draft=structuredClone(routine[day].exercises);$('edit-title').value=routine[day].title;editRows();$('editor').showModal()};$('close').onclick=$('cancel').onclick=()=>$('editor').close();$('add').onclick=()=>{draft.push(ex(0,'2 × 8 repeticiones'));editRows()};$('edit-form').onsubmit=event=>{event.preventDefault();routine[day].title=$('edit-title').value.trim();routine[day].exercises=draft;save('rutina-plan-ppl-turnos-v3',routine);$('editor').close();render();toast('Rutina guardada')};window.addEventListener('storage',event=>{if(event.key==='rutina-timer-v1'){timer=read(event.key,timer);tick()}if(event.key===weekKey){checks=read(weekKey,{});render()}if(event.key==='rutina-plan-ppl-turnos-v3'){routine=read(event.key,routine);render()}});document.addEventListener('visibilitychange',tick);$('custom').value=timer.duration;render();tick();setInterval(tick,250);

$('image-close').onclick=()=>$('image-view').close();
