'use strict';
const guideDialog=document.createElement('dialog');guideDialog.id='guide';guideDialog.innerHTML=`<div class="modal-heading"><h2 id="guide-title">Guía con voz</h2><button id="guide-close" aria-label="Cerrar guía">✕</button></div><details class="guide-technique"><summary>Técnica</summary><p id="guide-technique"></p></details><details class="guide-options"><summary>Ajustar series y ritmo</summary><div id="guide-settings"><label>Series<input id="guide-sets" type="number" min="1" max="10" value="2"></label><label>Repeticiones <input id="guide-reps" type="number" min="1" max="30" value="8"></label><label>Primer movimiento (s)<input id="guide-first" type="number" min="1" max="10" value="2"></label><label>Pausa (s)<input id="guide-hold" type="number" min="0" max="10" value="2"></label><label>Regreso (s)<input id="guide-return" type="number" min="1" max="10" value="2"></label><label>Descanso entre series (s)<input id="guide-rest" type="number" min="1" max="600" value="120"></label></div></details><p id="guide-summary"></p><label class="voice-choice"><input id="guide-voice" type="checkbox" checked> Voz activada</label><button id="guide-test" type="button">Probar voz</button><p id="guide-audio-status" role="status" hidden></p><div id="guide-cue" role="status" aria-live="polite">Prepárate</div><div id="guide-time" role="timer">—</div><p id="guide-count"></p><button id="guide-go" class="primary">Comenzar guía</button><div class="timer-actions"><button id="guide-pause" disabled>Pausar guía</button><button id="guide-stop" disabled>Terminar guía</button></div><p class="base-note">Mantén la pantalla abierta. La guía se pausa al cambiar de aplicación.</p>`;document.body.append(guideDialog);
let guideExercise,guideSteps=[],guideIndex=0,guideEnd=0,guideLeft=0,guideStatus='idle',guideWake=null;
const movement=[['Baja','Sube'],['Baja','Empuja'],['Tira','Vuelve'],['Baja','Sube'],['Tira al pecho','Vuelve'],['Empuja','Baja'],['Eleva','Baja'],['Extiende','Vuelve'],['Sube','Baja'],['Baja','Sube'],['Camina','Camina'],['Extiende','Vuelve'],['Redondea','Extiende'],['Mantén','Relaja'],['Baja','Sube'],['Eleva la cadera','Baja'],['Eleva los talones','Baja'],['Baja','Empuja'],['Tira','Vuelve'],['Abre','Vuelve'],['Sube','Baja'],['Baja','Extiende'],['Aleja los talones','Acerca los talones'],['Eleva la cadera','Baja'],['Baja','Sube'],['Eleva los talones','Baja']];
function words(n){return ['cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez'][n]||String(n)}
function audioProblem(){const status=$('guide-audio-status');status.hidden=false;status.textContent='No se pudo reproducir el audio. Sube el volumen y pulsa Probar voz para reintentar.'}
function speakGuide(text){if(!$('guide-voice').checked)return;try{playVoice(text)}catch{audioProblem();pauseGuide()}}
$('guide-test').after(voicePlayer);
let voiceTicket=0;
$('guide-test').onclick=()=>{const ticket=++voiceTicket;$('guide-test').disabled=true;$('guide-audio-status').hidden=false;$('guide-audio-status').textContent='Cargando voz…';try{readyVoice();if(ticket!==voiceTicket||!guideDialog.open)return;playVoice('La voz está lista. Baja en tres segundos. Sube en dos segundos');$('guide-audio-status').textContent='Iniciando audio…';}catch{audioProblem()}finally{$('guide-test').disabled=false}};
async function wakeGuide(){try{if('wakeLock' in navigator&&document.visibilityState==='visible')guideWake=await navigator.wakeLock.request('screen')}catch{}}
function releaseGuide(){guideWake?.release().catch(()=>{});guideWake=null}
function guideValues(){const ids=['sets','reps','first','hold','return','rest'];const out={};for(const id of ids){const input=$('guide-'+id),n=Number(input.value);if(!Number.isInteger(n)||n<Number(input.min)||n>Number(input.max)){input.reportValidity();return null}out[id]=n}return out}
function guideTempo(image){const loweringFirst=[0,1,3,9,14,17,21,22,24].includes(image);return {first:loweringFirst?3:2,hold:[2,4,15,16,18,23,25].includes(image)?1:0,return:loweringFirst?2:3}}
function guideSummary(){const v=guideValues();if(!v)return;const m=movement[guideExercise.image];$('guide-summary').textContent=guideExercise.work?`Tiempo: ${guideExercise.work} segundos. ${v.sets} series, descanso de ${v.rest} segundos.`:`${m[0]} en ${v.first} s → ${v.hold?'aguanta '+v.hold+' s → ':''}${m[1].toLowerCase()} en ${v.return} s. ${v.sets} × ${v.reps}${[9,11,14,24].includes(guideExercise.image)?' por lado':''}.`;}
window.openGuide=e=>{stopGuide(false);guideExercise=structuredClone(e);$('guide-title').textContent=e.name;$('guide-technique').textContent=e.tip;const remembered=read('rutina-guide-v4-'+e.id+'-'+trainingPhase,null);const matched=e.dose.match(/(\d+)\s*×\s*(\d+)/);$('guide-sets').value=remembered?.sets||Number(matched?.[1]||1);$('guide-reps').value=remembered?.reps||Number(matched?.[2]||8);const defaults=guideTempo(e.image);for(const id of ['first','hold','return'])$('guide-'+id).value=remembered?.[id]??defaults[id];$('guide-rest').value=remembered?.rest??e.seconds;for(const id of ['reps','first','hold','return'])$('guide-'+id).parentElement.hidden=!!e.work;$('guide-cue').textContent='Prepárate';$('guide-time').textContent='—';$('guide-count').textContent='';guideSummary();guideDialog.showModal();$('guide-audio-status').hidden=true;};
function addStep(cue,seconds,count=''){if(seconds>0)guideSteps.push({cue,seconds,count})}
function buildGuide(v){guideSteps=[];const m=movement[guideExercise.image];addStep('Prepárate. Comenzamos en cinco segundos',5);for(let set=1;set<=v.sets;set++){addStep(`Serie ${set}. Colócate`,3,`Serie ${set} de ${v.sets}`);if(guideExercise.work){addStep(`${guideExercise.image===10?'Camina a tu ritmo':'Mantén la posición'} durante ${guideExercise.work} segundos`,guideExercise.work,`Serie ${set} de ${v.sets}`)}else{const sides=[9,11,14,24].includes(guideExercise.image)?['lado derecho','lado izquierdo']:[''];for(const side of sides){if(side)addStep(`Prepara el ${side}`,4);for(let rep=1;rep<=v.reps;rep++){const count=`Serie ${set}/${v.sets} · Repetición ${rep}/${v.reps}${side?' · '+side:''}`;addStep(`${m[0]} en ${words(v.first)} segundos`,v.first,count);addStep(`Aguanta ${words(v.hold)} segundos`,v.hold,count);addStep(`${m[1]} en ${words(v.return)} segundos`,v.return,count)}}}if(set<v.sets){addStep(`Serie terminada. Descansa ${v.rest} segundos`,v.rest>5?v.rest-5:v.rest);if(v.rest>5)addStep('Prepara la siguiente serie. Cinco segundos',5)}}}
function showStep(){const step=guideSteps[guideIndex];if(!step){guideStatus='finished';releaseGuide();$('guide-cue').textContent='Ejercicio terminado';$('guide-time').textContent='✓';$('guide-count').textContent='Series completadas';speakGuide('Ejercicio terminado. Buen trabajo');checks[guideExercise.id]=true;save(weekKey,checks);render();setGuideControls();return}guideEnd=performance.now()+step.seconds*1000;$('guide-cue').textContent=step.cue;$('guide-count').textContent=step.count;speakGuide(step.cue);guideTick()}
function setGuideControls(){const active=['running','paused'].includes(guideStatus);$('guide-go').disabled=active||guideStatus==='loading';$('guide-test').disabled=active||guideStatus==='loading';$('guide-pause').disabled=!active;$('guide-stop').disabled=!active;$('guide-pause').textContent=guideStatus==='paused'?'Continuar guía':'Pausar guía';document.querySelectorAll('#guide-settings input').forEach(i=>i.disabled=active)}
function stopGuide(say=true){voiceTicket++;guideStatus='idle';stopVoice();releaseGuide();setGuideControls();if(say){$('guide-cue').textContent='Guía terminada sin marcar el ejercicio';$('guide-time').textContent='—'}}
function pauseGuide(){if(guideStatus!=='running')return;guideLeft=Math.max(0,guideEnd-performance.now());guideStatus='paused';stopVoice();releaseGuide();$('guide-cue').textContent='En pausa';setGuideControls()}
function guideTick(){if(guideStatus!=='running')return;const left=guideEnd-performance.now();if(left<=0){guideIndex++;showStep();return}$('guide-time').textContent=Math.ceil(left/1000)+' s'}
$('guide-go').onclick=()=>{const v=guideValues();if(!v)return;const ticket=++voiceTicket;guideStatus='loading';setGuideControls();try{if($('guide-voice').checked)readyVoice();if(ticket!==voiceTicket||!guideDialog.open)return;$('guide-audio-status').hidden=true;}catch{guideStatus='idle';setGuideControls();audioProblem();return;}save('rutina-guide-v4-'+guideExercise.id+'-'+trainingPhase,v);if(timer.status==='running'){timer.remaining=remaining();timer.status='paused';persistTimer();tick()}buildGuide(v);guideIndex=0;guideStatus='running';wakeGuide();setGuideControls();showStep()};$('guide-pause').onclick=()=>{if(guideStatus==='running')pauseGuide();else if(guideStatus==='paused'){guideStatus='running';guideEnd=performance.now()+guideLeft;wakeGuide();setGuideControls();$('guide-cue').textContent=guideSteps[guideIndex].cue;speakGuide(guideSteps[guideIndex].cue);guideTick()}};$('guide-stop').onclick=()=>stopGuide();$('guide-close').onclick=()=>guideDialog.close();guideDialog.addEventListener('close',()=>stopGuide(false));guideDialog.addEventListener('cancel',()=>stopGuide(false));$('guide-voice').onchange=()=>{if(!$('guide-voice').checked){stopVoice();return}try{readyVoice();if(guideStatus==='running')speakGuide(guideSteps[guideIndex].cue)}catch{audioProblem();pauseGuide()}};document.querySelectorAll('#guide-settings input').forEach(i=>i.onchange=guideSummary);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGuide()});setInterval(guideTick,100);
