'use strict';
const guideDialog=document.createElement('dialog');guideDialog.id='guide';guideDialog.innerHTML=`<div class="modal-heading"><h2 id="guide-title">Guía con voz</h2><button id="guide-close" aria-label="Cerrar guía">✕</button></div><p id="guide-technique"></p><div id="guide-settings"><label>Series<input id="guide-sets" type="number" min="1" max="10" value="2"></label><label>Repeticiones <input id="guide-reps" type="number" min="1" max="30" value="8"></label><label>Primer movimiento (s)<input id="guide-first" type="number" min="1" max="10" value="2"></label><label>Pausa (s)<input id="guide-hold" type="number" min="0" max="10" value="2"></label><label>Regreso (s)<input id="guide-return" type="number" min="1" max="10" value="2"></label><label>Descanso entre series (s)<input id="guide-rest" type="number" min="1" max="600" value="120"></label></div><p id="guide-summary"></p><label class="voice-choice"><input id="guide-voice" type="checkbox" checked> Voz activada</label><div id="guide-cue" role="status" aria-live="polite">Prepárate</div><div id="guide-time" role="timer">—</div><p id="guide-count"></p><button id="guide-go" class="primary">Comenzar guía</button><div class="timer-actions"><button id="guide-pause" disabled>Pausar guía</button><button id="guide-stop" disabled>Terminar guía</button></div><p class="base-note">Mantén esta pantalla abierta para escuchar la guía. Intentaremos mantenerla encendida. La guía se pausa si cambias de aplicación. Respira durante el movimiento; no fuerces una repetición para seguir la voz.</p>`;document.body.append(guideDialog);
let guideExercise,guideSteps=[],guideIndex=0,guideEnd=0,guideLeft=0,guideStatus='idle',guideWake=null;
const movement=[['Baja','Sube'],['Baja','Empuja'],['Tira','Vuelve'],['Baja','Sube'],['Tira al pecho','Vuelve'],['Empuja','Baja'],['Eleva','Baja'],['Extiende','Vuelve'],['Sube','Baja'],['Baja','Sube'],['Camina','Camina'],['Extiende','Vuelve'],['Redondea','Extiende'],['Mantén','Relaja']];
function words(n){return ['cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez'][n]||String(n)}
function speakGuide(text){if(!$('guide-voice').checked||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('es'));if(voice)u.voice=voice;u.lang=voice?.lang||'es-ES';u.rate=1.15;speechSynthesis.speak(u)}
async function wakeGuide(){try{if('wakeLock' in navigator&&document.visibilityState==='visible')guideWake=await navigator.wakeLock.request('screen')}catch{}}
function releaseGuide(){guideWake?.release().catch(()=>{});guideWake=null}
function guideValues(){const ids=['sets','reps','first','hold','return','rest'];const out={};for(const id of ids){const input=$('guide-'+id),n=Number(input.value);if(!Number.isInteger(n)||n<Number(input.min)||n>Number(input.max)){input.reportValidity();return null}out[id]=n}return out}
function guideSummary(){const v=guideValues();if(!v)return;const m=movement[guideExercise.image];$('guide-summary').textContent=guideExercise.work?`Tiempo: ${guideExercise.work} segundos. ${v.sets} series, descanso de ${v.rest} segundos.`:`${m[0]} en ${v.first} s → aguanta ${v.hold} s → ${m[1].toLowerCase()} en ${v.return} s. ${v.sets} × ${v.reps}${[9,11].includes(guideExercise.image)?' por lado':''}.`;}
window.openGuide=e=>{stopGuide(false);guideExercise=structuredClone(e);$('guide-title').textContent=e.name;$('guide-technique').textContent=e.tip;const remembered=read('rutina-guide-'+e.id,null);const matched=e.dose.match(/(\d+)\s*×\s*(\d+)/);$('guide-sets').value=remembered?.sets||Number(matched?.[1]||1);$('guide-reps').value=remembered?.reps||Number(matched?.[2]||8);for(const id of ['first','hold','return'])$('guide-'+id).value=remembered?.[id]??2;$('guide-rest').value=remembered?.rest??e.seconds;for(const id of ['reps','first','hold','return'])$('guide-'+id).parentElement.hidden=!!e.work;$('guide-cue').textContent='Prepárate';$('guide-time').textContent='—';$('guide-count').textContent='';guideSummary();guideDialog.showModal();if(!('speechSynthesis'in window)){ $('guide-voice').checked=false;$('guide-summary').textContent+=' Tu navegador no admite voz; usa las señales visuales.'}};
function addStep(cue,seconds,count=''){if(seconds>0)guideSteps.push({cue,seconds,count})}
function buildGuide(v){guideSteps=[];const m=movement[guideExercise.image];addStep('Prepárate. Comenzamos en cinco segundos',5);for(let set=1;set<=v.sets;set++){addStep(`Serie ${set}. Colócate`,3,`Serie ${set} de ${v.sets}`);if(guideExercise.work){addStep(`${guideExercise.image===10?'Camina a tu ritmo':'Mantén la posición'} durante ${guideExercise.work} segundos`,guideExercise.work,`Serie ${set} de ${v.sets}`)}else{const sides=[9,11].includes(guideExercise.image)?['lado derecho','lado izquierdo']:[''];for(const side of sides){if(side)addStep(`Prepara el ${side}`,4);for(let rep=1;rep<=v.reps;rep++){const count=`Serie ${set}/${v.sets} · Repetición ${rep}/${v.reps}${side?' · '+side:''}`;addStep(`${m[0]} en ${words(v.first)} segundos`,v.first,count);addStep(`Aguanta ${words(v.hold)} segundos`,v.hold,count);addStep(`${m[1]} en ${words(v.return)} segundos`,v.return,count)}}}if(set<v.sets){addStep(`Serie terminada. Descansa ${v.rest} segundos`,v.rest>5?v.rest-5:v.rest);if(v.rest>5)addStep('Prepara la siguiente serie. Cinco segundos',5)}}}
function showStep(){const step=guideSteps[guideIndex];if(!step){guideStatus='finished';releaseGuide();$('guide-cue').textContent='Ejercicio terminado';$('guide-time').textContent='✓';$('guide-count').textContent='Series completadas';speakGuide('Ejercicio terminado. Buen trabajo');checks[guideExercise.id]=true;save(weekKey,checks);render();setGuideControls();return}guideEnd=performance.now()+step.seconds*1000;$('guide-cue').textContent=step.cue;$('guide-count').textContent=step.count;speakGuide(step.cue);guideTick()}
function setGuideControls(){const active=['running','paused'].includes(guideStatus);$('guide-go').disabled=active;$('guide-pause').disabled=!active;$('guide-stop').disabled=!active;$('guide-pause').textContent=guideStatus==='paused'?'Continuar guía':'Pausar guía';document.querySelectorAll('#guide-settings input').forEach(i=>i.disabled=active)}
function stopGuide(say=true){guideStatus='idle';window.speechSynthesis?.cancel();releaseGuide();setGuideControls();if(say){$('guide-cue').textContent='Guía terminada sin marcar el ejercicio';$('guide-time').textContent='—'}}
function pauseGuide(){if(guideStatus!=='running')return;guideLeft=Math.max(0,guideEnd-performance.now());guideStatus='paused';window.speechSynthesis?.cancel();releaseGuide();$('guide-cue').textContent='En pausa';setGuideControls()}
function guideTick(){if(guideStatus!=='running')return;const left=guideEnd-performance.now();if(left<=0){guideIndex++;showStep();return}$('guide-time').textContent=Math.ceil(left/1000)+' s'}
$('guide-go').onclick=()=>{const v=guideValues();if(!v)return;save('rutina-guide-'+guideExercise.id,v);if(timer.status==='running'){timer.remaining=remaining();timer.status='paused';persistTimer();tick()}buildGuide(v);guideIndex=0;guideStatus='running';wakeGuide();setGuideControls();showStep()};$('guide-pause').onclick=()=>{if(guideStatus==='running')pauseGuide();else if(guideStatus==='paused'){guideStatus='running';guideEnd=performance.now()+guideSteps[guideIndex].seconds*1000;wakeGuide();setGuideControls();$('guide-cue').textContent=guideSteps[guideIndex].cue;speakGuide(guideSteps[guideIndex].cue);guideTick()}};$('guide-stop').onclick=()=>stopGuide();$('guide-close').onclick=()=>guideDialog.close();guideDialog.addEventListener('close',()=>stopGuide(false));guideDialog.addEventListener('cancel',()=>stopGuide(false));$('guide-voice').onchange=()=>{if(!$('guide-voice').checked)window.speechSynthesis?.cancel()};document.querySelectorAll('#guide-settings input').forEach(i=>i.onchange=guideSummary);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGuide()});setInterval(guideTick,100);
