'use strict';
const logKey='rutina-training-log-v1';
let trainingLog=read(logKey,[]);if(!Array.isArray(trainingLog))trainingLog=[];
const logDialog=document.createElement('dialog');logDialog.id='training-log';logDialog.innerHTML=`<div class="modal-heading"><h2 id="log-title">Registro de entrenamiento</h2><button id="log-close" aria-label="Cerrar registro">✕</button></div><p class="base-note">Registra lo que hiciste, no lo planificado. Los kilos y repeticiones pueden cambiar entre series.</p><form id="log-form"><div class="log-meta"><label>Fecha<input id="log-date" type="date" required></label><label>Cómo cuentas el peso<select id="log-basis"><option value="each">Kg por mancuerna</option><option value="total">Kg totales (incluye barra)</option><option value="machine">Kg indicados en la polea</option><option value="body">Sin peso añadido</option></select></label></div><p id="log-help"></p><div id="log-sets"></div><button id="log-add" type="button">+ Añadir serie</button><label class="log-notes">Notas (opcional)<input id="log-notes" maxlength="300" placeholder="Cómo te sentiste, ajuste de la máquina…"></label><div class="modal-footer"><button id="log-new" type="button">Nuevo registro</button><button class="primary" type="submit" id="log-save">Guardar registro</button></div></form><h3>Historial de este ejercicio</h3><div id="log-history"></div><p class="base-note">Guardado en este navegador. No se sincroniza entre dispositivos; si borras sus datos, se pierde el historial.</p>`;document.body.append(logDialog);
let logExercise,editingLog=null;
const basisLabels={each:'kg por mancuerna',total:'kg totales',machine:'kg en polea',body:'sin peso añadido'};
const exerciseLogKey=e=>e.historyKey||`${e.image}:${e.name.trim().toLocaleLowerCase('es')}`;
function matchingLogs(){return trainingLog.filter(r=>r.exerciseKey===exerciseLogKey(logExercise)||r.exerciseId===logExercise.id).sort((a,b)=>b.date.localeCompare(a.date)||b.savedAt.localeCompare(a.savedAt))}
function helpLog(){const body=$('log-basis').value==='body';$('log-help').textContent=body?'Anota las repeticiones. El peso añadido será 0 kg.':$('log-basis').value==='each'?'Si usaste dos mancuernas de 10 kg, registra 10 kg por mancuerna.':'Mantén el mismo criterio para comparar tus sesiones.';document.querySelectorAll('.log-weight').forEach(input=>{input.disabled=body;if(body)input.value=0})}
function addLogSet(value={weight:'',reps:''}){const row=document.createElement('div');row.className='log-set';const number=document.createElement('span');number.className='log-set-number';const weightLabel=document.createElement('label');weightLabel.textContent='Peso (kg)';const weight=document.createElement('input');weight.className='log-weight';weight.type='number';weight.min='0';weight.max='2000';weight.step='any';weight.inputMode='decimal';weight.required=true;weight.value=value.weight;weightLabel.append(weight);const repLabel=document.createElement('label');repLabel.textContent='Repeticiones realizadas';const reps=document.createElement('input');reps.className='log-reps';reps.type='number';reps.min='1';reps.max='500';reps.step='1';reps.inputMode='numeric';reps.required=true;reps.value=value.reps;repLabel.append(reps);const remove=document.createElement('button');remove.type='button';remove.textContent='✕';remove.onclick=()=>{if($('log-sets').children.length<=1){toast('Registra al menos una serie.');return}row.remove();numberLogSets()};row.append(number,weightLabel,repLabel,remove);$('log-sets').append(row);numberLogSets();helpLog()}
function numberLogSets(){document.querySelectorAll('.log-set').forEach((r,i)=>{r.querySelector('.log-set-number').textContent='Serie '+(i+1);r.querySelector('button').setAttribute('aria-label','Quitar serie '+(i+1))})}
function freshLog(){editingLog=null;$('log-date').value=new Date().toLocaleDateString('en-CA');const date=new Date();$('log-date').value=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;$('log-date').max=$('log-date').value;$('log-notes').value='';const latest=matchingLogs()[0];$('log-basis').value=latest?.basis??logExercise.weightBasis??([0,1,3,5,6,8,9,17,18,19,20,24,25].includes(logExercise.image)?'each':[21,23].includes(logExercise.image)?'total':[2,4,7].includes(logExercise.image)?'machine':'body');$('log-sets').replaceChildren();const count=Math.min(10,Number(logExercise.dose.match(/(\d+)\s*×/)?.[1]||1));for(let i=0;i<count;i++)addLogSet({weight:latest?.sets[i]?.weight??'',reps:''});$('log-save').textContent='Guardar registro';helpLog()}
function writeTrainingLog(next){try{localStorage.setItem(logKey,JSON.stringify(next));trainingLog=next;return true}catch{toast('No se pudo guardar. Revisa el espacio disponible del navegador.');return false}}
function historyLog(){const target=$('log-history');target.replaceChildren();const records=matchingLogs();if(!records.length){const empty=document.createElement('p');empty.className='base-note';empty.textContent='Todavía no registraste este ejercicio.';target.append(empty);return}for(const record of records){const item=document.createElement('article');item.className='log-entry';const date=document.createElement('strong');date.textContent=new Date(record.date+'T12:00:00').toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric'});const sets=document.createElement('p');sets.textContent=record.sets.map((s,i)=>`Serie ${i+1}: ${record.basis==='body'?'sin peso añadido':s.weight+' '+basisLabels[record.basis]} × ${s.reps} rep.`).join(' · ');item.append(date,sets);if(record.notes){const note=document.createElement('p');note.textContent=record.notes;item.append(note)}const edit=document.createElement('button');edit.textContent='Editar registro';edit.onclick=()=>{editingLog=record.id;$('log-date').value=record.date;$('log-basis').value=record.basis;$('log-notes').value=record.notes;$('log-sets').replaceChildren();record.sets.forEach(addLogSet);$('log-save').textContent='Guardar cambios';$('log-form').scrollIntoView({block:'start',behavior:'smooth'})};item.append(edit);target.append(item)}}
window.openTrainingLog=e=>{logExercise=structuredClone(e);trainingLog=read(logKey,trainingLog);$('log-title').textContent=e.name;freshLog();historyLog();logDialog.showModal()};
$('log-close').onclick=()=>logDialog.close();$('log-add').onclick=()=>{if($('log-sets').children.length>=20){toast('Máximo 20 series por registro.');return}addLogSet()};$('log-new').onclick=freshLog;$('log-basis').onchange=helpLog;
$('log-form').onsubmit=event=>{event.preventDefault();if(!$('log-form').reportValidity())return;const sets=Array.from(document.querySelectorAll('.log-set')).map(row=>({weight:$('log-basis').value==='body'?0:Number(row.querySelector('.log-weight').value),reps:Number(row.querySelector('.log-reps').value)}));if(!sets.length||sets.some(s=>!Number.isFinite(s.weight)||s.weight<0||!Number.isInteger(s.reps)||s.reps<1)){toast('Revisa los pesos y repeticiones.');return}const record={id:editingLog||crypto.randomUUID(),exerciseId:logExercise.id,exerciseKey:exerciseLogKey(logExercise),name:logExercise.name,date:$('log-date').value,basis:$('log-basis').value,sets,notes:$('log-notes').value.trim(),savedAt:new Date().toISOString()};const current=read(logKey,trainingLog);const next=current.filter(r=>r.id!==record.id);next.push(record);if(!writeTrainingLog(next))return;editingLog=record.id;$('log-save').textContent='Guardar cambios';historyLog();toast('Registro guardado')};window.addEventListener('storage',event=>{if(event.key===logKey){trainingLog=read(logKey,[]);if(logDialog.open)historyLog()}});
